version: "3.9"
services:
  traefik:
    image: traefik:v3.1
    command: --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/letsencrypt/acme.json
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    networks: [webnet]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [webnet]

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks: [webnet]

  api:
    build:
      context: ./backend
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
      CORS_ORIGINS: '["https://${DOMAIN}"]'
      REDIS_URL: redis://redis:6379/0
      RATE_LIMIT_WINDOW_SECONDS: 60
      RATE_LIMIT_MAX_REQUESTS: 60
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.okr-api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.okr-api.entrypoints=websecure"
      - "traefik.http.routers.okr-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.okr-api.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.okr-api-https.redirectscheme.scheme=https"
      - "traefik.http.routers.okr-api-web.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.okr-api-web.entrypoints=web"
      - "traefik.http.routers.okr-api-web.middlewares=okr-api-https"
    depends_on:
      - db
      - redis
    networks: [webnet]

  web:
    build:
      context: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.okr-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.okr-web.entrypoints=websecure"
      - "traefik.http.routers.okr-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.okr-web.loadbalancer.server.port=80"
      - "traefik.http.middlewares.okr-web-https.redirectscheme.scheme=https"
      - "traefik.http.routers.okr-web-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.okr-web-web.entrypoints=web"
      - "traefik.http.routers.okr-web-web.middlewares=okr-web-https"
    depends_on:
      - api
    networks: [webnet]

networks:
  webnet:

volumes:
  mysql_data:
  redis_data:
