version: "3.9"
services:
  caddy:
    image: caddy:2.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    networks: [webnet]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [webnet]

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks: [webnet]

  api:
    build:
      context: ./backend
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
      CORS_ORIGINS: '["https://${DOMAIN}"]'
      REDIS_URL: redis://redis:6379/0
      RATE_LIMIT_WINDOW_SECONDS: 60
      RATE_LIMIT_MAX_REQUESTS: 60
    depends_on:
      - db
      - redis
    networks: [webnet]

  web:
    build:
      context: ./frontend
    depends_on:
      - api
    networks: [webnet]

networks:
  webnet:

volumes:
  mysql_data:
  redis_data:
  caddy_data:
  caddy_config:
